[versions]
openrewrite = "7.26.0"

[libraries]
# Used in recipes/build.gradle.kts
openrewrite-java17 = { module = "org.openrewrite:rewrite-java-17" }
lombok = { module = "org.projectlombok:lombok", version = "1.18.42" }

[plugins]
openrewrite = { id = "org.openrewrite.rewrite", version.ref = "openrewrite" }
